### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by rexuedeliulianjun** [sysuxuhr/Brinson-Model-mutiple#1]
您好，很佩服您使用python实现业绩归因，能提两个小建议吗？
1、建议提供底层行业数据处理模板的excel，以及一些数据结构，方便其他人参考学习；
2、Brinson_function.py是否可以修改完善后直接调用，读入数据后，调用该模块即可得到结果。

**Comment by sysuxuhr** [comment]
1、数据是内部机密，因此无法共享；
2、目前还不会生成调用包。。
